### ISSUE TITLE
Tracer has apparently stopped recognising updated packages in Fedora 38

### ISSUE THREAD

**Issue by DrReD** [FrostyX/tracer#197]
Tracer has apparently stopped recognising updated-and-running packages in Fedora 38, except for the kernel.

Furthermore, I can't find python3-tracer between the packages available in fedora-bugzilla.

Related packages on Fedora:
tracer-common-0.7.9-1.fc38.noarch
python3-tracer-0.7.9-1.fc38.noarch

**Comment by FrostyX** [comment]
Thank you for the reply @DrReD,

> Furthermore, I can't find python3-tracer between the packages available in fedora-bugzilla.

This is strange. I could find it in the `Red Hat Enterprise Linux 8` product but not in `Fedora`.

> Tracer has apparently stopped recognising updated-and-running packages in Fedora 38, except for the kernel.

I am still on Fedora 37, so I did this quick test:

```
$ docker run -it fedora:38 bash
[root@9b63edd1331d /]# dnf -y install nano tracer
[root@9b63edd1331d /]# nano
^T^Z
[root@9b63edd1331d /]# tracer
You should restart:
  * These applications manually:
      nano

Additionally, there are:
  - 1 processes requiring restart of your session (i.e. Logging out & Logging in again)
```

So it could find it. The `1 processes requiring restart of your session (i.e. Logging out & Logging in again)` is probably false positive but let's ignore it for the time being.

Do you think it works for me because I am trying it in docker and I should try a real F38 instead?

**Comment by FrostyX** [comment]
> Tracer has apparently stopped recognising updated-and-running packages in Fedora 38

I think I found the issue. We were using wrong DNF database path. Since a70893a, the `/usr/lib/sysimage/dnf/history.sqlite` was being used. But that doesn't exist on my Fedora 38. IMHO the correct database path is `/var/lib/dnf/history.sqlite`.

I am sending a patch to fix this.

**Comment by DrReD** [comment]
Thank you very much.
Today's updates in fedora carry your fix and solve the problem.

note:
python3-tracer-1.0-1.fc38.noarch tracer-common-1.0-1.fc38.noarch
