### ISSUE TITLE
Implement and document exit codes for use with scripts

### ISSUE THREAD

**Issue by peccuflo** [FrostyX/tracer#46]
I just started looking into using Tracer in conjunction with my update script. I noticed a shortcoming which I hope can be addressed in a future release ...

Tracer does not appear to have any documented exit codes which could be used by an update script for the purpose of informing the user when it is necessary to log-off or reboot a system. I would suggest something along the lines of the following ...
0 -- no logoff or reboot is necessary (returned if no software needs to be restarted)
1 -- logoff is necessary (returned if at least one piece of software needs to be restarted, and none require a reboot)
2 -- reboot is necessary (returned if at least one piece of software requires a reboot)

There could be a lot more exit codes if you wanted to be more specific, but I think these would cover most use cases.

**Comment by FrostyX** [comment]
I find the usecase very reasonable, but I think that I disagree with suggested implementation. AFAIK status codes are for error statuses. In meaning of zero = program worked correctly and non-zero = program failed because of something.

I would rather provide methods to solve the usecase through [Tracer API](http://docs.tracer-package.com/en/latest/api/). For an example somehow like that:

    from tracer.query import Query
    q = Query()
    a = q.affected_applications().get()
    if a.needs_reboot():
        pass

Where `a.needs_reboot()` will return filtered collection of applications which require reboot. So it can be easily used for listing them, or determining boolean whether are there any.

In case your update script is written in python, this solution will be very comfortable. In case of shell script, you can for instance write a very short wrapper in python which uses the API, examines affected applications and sets the desired status code. It would be like 10 lines of code.

What is your opinion on this?

**Comment by peccuflo** [comment]
Well, I personally feel that such an interpretation of exit status codes is unnecessarily limiting with no realistic upside. It's very common for commands to return non-error status codes. dnf itself does, for example with "dnf check-update" returning 100 if updates are available and 0 if updates are not available (exit status 1 indicates an error). Another example is clamav's clamscan, which returns 1 if a virus is found and 0 if no virus is found (2 if there's an error). I could go on....

So that's my take. But I respect your position and it's your project, so if you disagree I'm sure I can use the API instead; it just seems like an unnecessary complication from my perspective.

**Comment by FrostyX** [comment]
Ok, well, you are probably right. We can have status codes for indicating such things. But it will need change in Tracer's DNF plugin, because it takes all non-zero as error.

I am not maintainer of the plugins package, so I can only code that thing and wait how and when its released. I will think about it, talk with some people and let you know.

**Comment by FrostyX** [comment]
What do you think? Can you please try it and let me know whether it covers your use-case? Thanks! :-)

<https://tracer.readthedocs.org/en/latest/api/#exit-codes>

**Comment by peccuflo** [comment]
Looks like it will work very nicely.

For my use case, I think I can treat 101 and 103 both as "logout required" and 102 and 104 as "reboot required" -- does that sound right? (i don't want to complicate things by telling the user to take more specific actions than these)

this does bring up a few questions for me though ...

103 Session restart needed ... does this mean the current user needs to restart their session (of course for now that would be root, since tracer currently only runs as root), or that some/all users need to restart their sessions? should there be additional status codes to differentiate? (e.g. "only current user needs to restart their session" / "only other user(s) need to restart their sessions" / "current user and other user(s) need to restart their sessions")

102 Found some affected daemons ... what qualifies as a "daemon" to tracer?

101 Found some affected applications ... same as my question for 103 ... does / should tracer distinguish which user is running the application?

**Comment by FrostyX** [comment]
> For my use case, I think I can treat 101 and 103 both as "logout required" and 102 and 104 as "reboot required" -- does that sound right?

Well, it is kind of overkill, but it will absolutely work. For instance 102 will indicate that some daemon needs restarting, and that can be done running `service foo restart`. Rebooting because of this is not necessary, but yeah, it will solve it.

> 103 Session restart needed ... does this mean the current user needs to restart their session (of course for now that would be root, since tracer currently only runs as root), or that some/all users need to restart their sessions?

Actually when you run tracer with sudo, it will recognize which user called it, so it prints what the actual user should do. When you want to specify some different user, please see <http://docs.tracer-package.com/en/latest/manpage/#users>

> 102 Found some affected daemons ... what qualifies as a "daemon" to tracer?

There is this file <https://github.com/FrostyX/tracer/blob/master/data/applications.xml> which specifies  it. You can configure your own apps in same format, in `~/.config/tracer/applications.xml`. It should be documented, but it haven't been done yet. 

But also, since `0.6.1` version, it has some autodetect functionality, so when the application has `/usr/lib/systemd/system/{0}.service` file, it is considered to be a daemon.

**Comment by peccuflo** [comment]
cool, thanks! :-)

**Comment by FrostyX** [comment]
Do you want to modify the status codes behaviour somehow or can I close the issue and release new tracer version?

**Comment by peccuflo** [comment]
Looks good to me!

**Comment by FrostyX** [comment]
Ok, great. 
I am going to close the issue and release new tracer version.
